### ISSUE TITLE
Is there a way to post a Submission?

### ISSUE THREAD

**Issue by lmj0011** [KirkBushman/ARAW#4]
I'm trying to figure out how to post a [Submission](https://kirkbushman.github.io/ARAW/lib/com.kirkbushman.araw.models/-submission/index.html)

Does this library implement this?
Couldn't find it in the docs, if it so.
https://kirkbushman.github.io/ARAW/lib/alltypes/index.html

**Comment by KirkBushman** [comment]
Yes, it's under SubredditsClient. I suggest you check out the sample app, to have an easy example of how most stuff is implemented.

```kotlin

val client: RedditClient
client.subredditsClient.submit(
    subredditName = // subreddit name
    title = // title of the post
    kind = // [videogif, video, image, link, self]
    text = // text of the post
    url = // link to a website, if you need it.
    sendReplies = // whether to send replies in you inbox.
    isNsfw = // whether it is over 18
    isSpoiler = // whether it is spoiler
)
```
